### ISSUE TITLE
Possible bug: maximum execution time of script go back to 5 minutes even using a business account

### ISSUE THREAD

**Issue by htadashi** [tanaikech/RunAll#3]
Hi @tanaikech , thanks for this extremely useful library! :)

I have a business account that allows the execution of GAS scripts for more than 30 minutes. However, calling the functions from RunAll times out in 5 minutes. I am deploying my script as a WebApp and with the following options:
![image](https://user-images.githubusercontent.com/2355491/113235250-1cfd6a00-9279-11eb-9c12-4376bcf477e8.png)

Is there a workaround for this?

**Comment by tanaikech** [comment]
Thank you for replying. Unfortunately, I cannot test your situation using the business account. By this, I cannot think of the solution and workaround. This is due to my poor skill. I deeply apologize for this.

**Comment by htadashi** [comment]
Thanks for the quick reply! It is me who should deeply apologize 🙇🏻‍♂️ I didn't explain my problem clearly and thought it was a bug.

I researched further Google documentation, and it seems that the script.run request (made by the `fetchAll` method) is always [limited to 6 minutes](https://developers.google.com/apps-script/api/how-tos/execute#step_4_make_the_scriptrun_request). Though it is not explicitly stated in the documentation, this restriction seems to be also true even for business accounts which has 30 minutes execution time without the API. So it is not a bug from the library, just a limitation from GAS API. 

Thanks again for your time and your support (お世話になります).
